name: helloGithubAction

on: [push]

jobs : 
   build:
      runs-on: ubuntu-latest
      steps:
      -  name : 환영 인사 출력!!
         run: echo Hello, world!
      -  name: 디렉토리 출력!!
         run: ls -al   
      -  name: .Net 버젼 출력!!
         run: dotnet --version
      -  name: 루트 파일만 가져오기!! 이걸 안하면 코드 실행 못함
         uses: actions/checkout@v4
      -  name: .Net 코드 실행하기
         run: dotnet run --property WarningLevel=0 Test
